esphome:
  name: "pool-display"
  friendly_name: Pool Display
  platformio_options:
    build_dir: "C:\\esphome_build\\pool-display"
    build_path: "C:\\esphome_build\\pool-display"
    build_unflags:
      - "-DLVGL_USE_VG_LITE"
    build_flags:
      - "-DLVGL_USE_VG_LITE=0"
  on_boot:
    - priority: -100
      then:
        - wait_until:
            api.connected:
        - lambda: |-
            esp_reset_reason_t reason = esp_reset_reason();
            switch(reason) {
              case ESP_RST_POWERON:   ESP_LOGI("boot", "Reset: Power on"); break;
              case ESP_RST_BROWNOUT:  ESP_LOGE("boot", "Reset: BROWNOUT"); break;
              case ESP_RST_WDT:       ESP_LOGE("boot", "Reset: Watchdog"); break;
              case ESP_RST_PANIC:     ESP_LOGE("boot", "Reset: Panic/crash"); break;
              case ESP_RST_SW:        ESP_LOGI("boot", "Reset: Software"); break;
              case ESP_RST_DEEPSLEEP: ESP_LOGI("boot", "Reset: Deep sleep"); break;
              default:                ESP_LOGW("boot", "Reset: Unknown (%d)", reason); break;
            }  
       
   
  
esp32:
  variant: esp32p4
  engineering_sample: true
  framework:
    type: esp-idf
    version: 5.4.2
    advanced:
      enable_idf_experimental_features: true
  flash_size: 32MB
  cpu_frequency: 360MHz
  partitions: partitions.csv

ethernet:
  type: W5500
  mosi_pin: GPIO4
  miso_pin: GPIO5
  clk_pin: GPIO2
  cs_pin: GPIO3
  interrupt_pin: GPIO28
  reset_pin: GPIO29
  clock_speed: 20MHz



udp:
  addresses:
    - 192.168.13.6

psram:
  mode: hex
  speed: 200MHz

preferences:
  flash_write_interval: 5min

esp_ldo:
  - voltage: 2.5V
    channel: 3

safe_mode:
  num_attempts: 3
  reboot_timeout: 60s
  boot_is_good_after: 30s

logger:
  level: VERBOSE
  initial_level: INFO

debug:

ota:
  platform: esphome

api:
  reboot_timeout: 2min
  
web_server:
  port: 80

http_request:
  useragent: esphome/cyd
  timeout: 10s
  verify_ssl: False

syslog:
  port: 1514
  strip: true



packages:
  interfaces: !include pool-display/interface/interface_config.yaml
  fonts: !include pool-display/interface/fontscolors.yaml
  lvgl: !include pool-display/interface/lvgl_7_wave.yaml
  style: !include pool-display/interface/themes_styles.yaml


i2c:
  sda: GPIO07
  scl: GPIO08
  frequency: 400khz
  timeout: 10ms

display:
  - platform: mipi_dsi
    id: main_display
    model: WAVESHARE-ESP32-P4-WIFI6-TOUCH-LCD-7B
    reset_pin:
      number: 33
    update_interval: never
    auto_clear_enabled: false
   
    dimensions:
      width: 1024
      height: 600


touchscreen:
  - platform: gt911
    id: touch
    reset_pin: GPIO23
    update_interval: 100ms
    transform:
      swap_xy: false
      mirror_x: true
      mirror_y: true
    on_touch:
      then:
        - light.turn_on:
            id: backlight
        - script.execute: 
            id: backlight_off_timer
        - logger.log: "TOUCH DETECTED"    

# --- Backlight ---
output:
  - platform: ledc
    pin: 
      number: GPIO32
      inverted: true
    id: backlight_pwm
    frequency: 5000 Hz
    

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

script:
  - id: backlight_off_timer
    mode: restart
    then:
      - delay: 120s
      - light.turn_off: 
          id: backlight

select:
  - platform: logger
    name: "Log Level"
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Log level was manually updated to: %s"
            args: [ 'x.c_str()' ]    

time:
  - platform: homeassistant
    id: pool_time            
