esphome:
  name: "pool-display"
  friendly_name: Pool Display
  on_boot:
    - priority: 600
      then:
        - lambda: |-
            id(reboot_count)++;     
    - priority: -10
      then:
        - delay: 15s
        - lvgl.label.update:
            id: head_lbl_build
            text: !lambda |-
              return std::string("Build: ") + __DATE__ + " " + __TIME__;
    - priority: -100
      then:
        - delay: 10s
        - lambda: |-
            id(boot_complete) = true;
   
  
esp32:
  variant: esp32p4
  engineering_sample: true
  framework:
    type: esp-idf
    version: 5.4.2
    advanced:
      enable_idf_experimental_features: true
  flash_size: 32MB
  cpu_frequency: 360MHz

#ethernet:
#  type: W5500
#  mosi_pin: GPIO4
#  miso_pin: GPIO5
#  clk_pin: GPIO2
#  cs_pin: GPIO3
#  interrupt_pin: GPIO28
#  reset_pin: GPIO29
#  clock_speed: 20MHz
#  manual_ip:
#    static_ip: !secret pool_ip
#    gateway: !secret gateway
#    subnet: !secret subnet



psram:
  mode: hex
  speed: 200MHz

preferences:
  flash_write_interval: 5min

esp_ldo:
  - voltage: 2.5V
    channel: 3


logger:
  level: DEBUG

debug:

#ota:
#  platform: esphome

#api:

#captive_portal:
  
#web_server:
#  port: 80

#http_request:
#  useragent: esphome/cyd
#  timeout: 10s
#  verify_ssl: False





packages:

  globals: !include pool-display/globals.yaml
  heater: !include pool-display/heater.yaml
  hardware: !include pool-display/hardware.yaml
  chemistry: !include pool-display/chemistry.yaml
  pump: !include pool-display/pump.yaml
#  acid_dose: !include pool-display/acid_dose.yaml
  chlorinator: !include pool-display/chlorinator.yaml
#  schedule: !include pool-display/schedule.yaml
  interfaces: !include pool-display/interface/interface_config.yaml
  fonts: !include pool-display/interface/fontscolors.yaml
  lvgl: !include pool-display/interface/lvgl_7_wave.yaml
  style: !include pool-display/interface/themes_styles.yaml
  core: !include pool-display/core.yaml


