esphome:
  name: p4-test
  friendly_name: test

esp32:
  variant: esp32p4
  framework:
    type: esp-idf
    version: 5.4.2
    advanced:
      enable_idf_experimental_features: true
  flash_size: 32MB
  cpu_frequency: 360MHz

psram:
  mode: hex
  speed: 200MHz

logger:
  level: DEBUG

