







sensor:
  - platform: ads1115
    ads1115_id: ads0
    multiplexer: 'A0_GND'
    gain: 4.096
    name: "3v rail"
  - platform: ads1115
    ads1115_id: ads0
    multiplexer: 'A1_GND'
    gain: 2.048
    name: "5v rail 1"
    filters:
     - multiply: !lambda return 3;  
  - platform: ads1115
    ads1115_id: ads0
    multiplexer: 'A2_GND'
    gain: 2.048
    name: "5v rail 2"
    filters:
     - multiply: !lambda return 3;     
  - platform: ads1115
    ads1115_id: ads0
    multiplexer: 'A3_GND'
    gain: 4.096
    name: "12v rail"
    filters:
     - multiply: !lambda return 5;  


